/*
 * Copyright © 2026 IKE Network (support@ike.network)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package network.ike.richsurface.glossary;

import com.sparrowwallet.toucan.LifeHash;
import com.sparrowwallet.toucan.LifeHashVersion;
import dev.ikm.tinkar.entity.builder.KnowledgeSet;
import dev.ikm.tinkar.entity.builder.KnowledgeSet.Declaration;
import dev.ikm.tinkar.entity.builder.KnowledgeSetSource;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Comparator;
import java.util.List;
import java.util.ServiceLoader;

/**
 * Generates the AsciiDoc glossary for a knowledge set — the set's <em>doc projection</em>,
 * beside the code projection (bindings) and the KB projection (change set). For every
 * concept and pattern in the ledger it emits a <em>Koncept</em>: a LifeHash identicon
 * (data-URI PNG, generated by the same {@code toucan} library and algorithm version
 * Komet uses, so the badge is identical across the guide, Komet, and the Zulip/email
 * adapters) beside the component's fully qualified name, followed by its definition and
 * its public UUID.
 * <p>
 * The knowledge set is discovered via {@link ServiceLoader} over
 * {@link KnowledgeSetSource}; composition is store-free (the {@code declarations()} read
 * surface needs no datastore), so this runs as a plain generator with no providers on
 * the classpath. The output is a fragment (no document header) meant to be
 * {@code include::}d under a section the including document controls.
 * <p>
 * Invoked from the guide module at build time (an {@code exec} in {@code rich-surface-doc}
 * writes into {@code target/generated-sources/asciidoc}, the {@code {generated}} include
 * root). When a second knowledge set needs a glossary, this generalizes to a tinkar-side
 * {@code GlossaryMain} plus an {@code ike:knowledge-glossary} goal — the same shape as
 * bindings and export — kept out of tinkar-core because it depends on the identicon
 * library.
 */
public final class GlossaryGenerator {

    private GlossaryGenerator() {
    }

    /** LifeHash pixels-per-module; the VERSION2 grid is 32×32 modules, so 2 → 64×64 px. */
    private static final int MODULE_SIZE = 2;

    /**
     * Generates the glossary fragment.
     *
     * @param args {@code outputFile [sourceClassName]} — the AsciiDoc file to write, and
     *             optionally the {@link KnowledgeSetSource} class to select when the
     *             classpath provides more than one
     * @throws Exception if discovery, composition, or writing fails
     */
    public static void main(String[] args) throws Exception {
        if (args.length < 1 || args.length > 2) {
            throw new IllegalArgumentException("Usage: GlossaryGenerator <outputFile> [sourceClassName]");
        }
        Path outputFile = Path.of(args[0]);

        KnowledgeSetSource source;
        if (args.length == 2) {
            source = (KnowledgeSetSource) Class.forName(args[1], true,
                    GlossaryGenerator.class.getClassLoader()).getDeclaredConstructor().newInstance();
        } else {
            List<KnowledgeSetSource> found = new ArrayList<>();
            ServiceLoader.load(KnowledgeSetSource.class, GlossaryGenerator.class.getClassLoader())
                    .forEach(found::add);
            if (found.size() != 1) {
                throw new IllegalStateException("Expected exactly one KnowledgeSetSource on the classpath, found "
                        + found.size() + " — pass the implementation class name as the second argument");
            }
            source = found.getFirst();
        }

        KnowledgeSet knowledgeSet = source.compose();
        String adoc = render(knowledgeSet.declarations());

        Files.createDirectories(outputFile.toAbsolutePath().getParent());
        Files.writeString(outputFile, adoc);
        System.out.println("Glossary written: " + outputFile + " — "
                + knowledgeSet.declarations().size() + " entries from " + source.getClass().getName());
    }

    /**
     * Renders the glossary fragment: a Koncept description list per kind (concepts, then
     * patterns), each sorted by fully qualified name.
     *
     * @param declarations the set's declarations
     * @return the AsciiDoc fragment
     */
    static String render(List<Declaration> declarations) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by rich-surface-glossary — DO NOT EDIT.\n\n");
        renderGroup(sb, declarations, Declaration.Kind.CONCEPT, "Concepts");
        renderGroup(sb, declarations, Declaration.Kind.PATTERN, "Patterns");
        return sb.toString();
    }

    private static void renderGroup(StringBuilder sb, List<Declaration> declarations,
                                    Declaration.Kind kind, String heading) {
        List<Declaration> group = declarations.stream()
                .filter(d -> d.kind() == kind)
                .sorted(Comparator.comparing(Declaration::birthFqn))
                .toList();
        if (group.isEmpty()) {
            return;
        }
        sb.append('.').append(heading).append(" (").append(group.size()).append(")\n");
        sb.append("[glossary]\n");
        for (Declaration declaration : group) {
            String uuid = declaration.publicId().asUuidArray()[0].toString();
            String idString = declaration.publicId().idString();
            sb.append("image:data:image/png;base64,").append(identiconBase64(idString))
                    .append("[,24,24,role=\"identicon\"] *")
                    .append(escapeInline(declaration.birthFqn())).append("*::\n");
            sb.append(declaration.definition().map(GlossaryGenerator::escapeBlock)
                    .orElse("_No definition._")).append('\n');
            sb.append("+\n");
            sb.append("[.identifier]#`").append(uuid).append("`#\n\n");
        }
        sb.append('\n');
    }

    /**
     * Generates the LifeHash identicon for an id string as a base64-encoded PNG — the
     * same library, algorithm version, and input Komet uses.
     *
     * @param idString the {@code PublicId.idString()} — the LifeHash input
     * @return the base64-encoded PNG bytes
     */
    static String identiconBase64(String idString) {
        LifeHash.Image image = LifeHash.makeFromUTF8(idString, LifeHashVersion.VERSION2, MODULE_SIZE, false);
        BufferedImage buffered = LifeHash.getBufferedImage(image);
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            ImageIO.write(buffered, "png", baos);
            return Base64.getEncoder().encodeToString(baos.toByteArray());
        } catch (IOException e) {
            throw new RuntimeException("Failed to encode identicon PNG for " + idString, e);
        }
    }

    private static String escapeInline(String text) {
        // Neutralize the AsciiDoc emphasis/attribute characters that would break a
        // single-line dlist term; the FQN is a plain phrase in practice.
        return text.replace("*", "\\*");
    }

    private static String escapeBlock(String text) {
        return text.strip();
    }
}
