/*
 * Copyright © 2026 IKE Network (support@ike.network)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package network.ike.richsurface.glossary;

import dev.ikm.tinkar.common.id.PublicId;
import dev.ikm.tinkar.entity.builder.KnowledgeSet;
import dev.ikm.tinkar.entity.builder.KnowledgeSet.Declaration;
import dev.ikm.tinkar.entity.builder.KnowledgeSetSource;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.ServiceLoader;

/**
 * The doc projection of a knowledge set: extracts the standard {@code koncepts.yml} —
 * the definition source the {@code koncept-asciidoc-extension} renders into the standard
 * comprehensive glossary (identicon chips, textual and logical definitions, parents,
 * children, and identifiers). One entry per concept and pattern: label, definition,
 * kind, the taxonomy as a DL {@code axiom} and a {@code broader} parent list, and the
 * identity UUID.
 * <p>
 * This is the ledger extraction point. The same {@code koncepts.yml} schema is also the
 * plug point for a general knowledge-base extraction (a change set loaded into an
 * ephemeral store, walked for descriptions and stated axioms) — the rendering standard
 * is the same either way. The generator only walks the ledger's store-free
 * {@code declarations()} read surface and needs no identicon library; the extension
 * renders identicons at doc build time.
 */
public final class GlossaryGenerator {

    private GlossaryGenerator() {
    }

    /**
     * Generates the standard koncepts YAML for the knowledge set.
     *
     * @param args {@code konceptsYmlFile [sourceClassName]}
     * @throws Exception if discovery, composition, or writing fails
     */
    public static void main(String[] args) throws Exception {
        if (args.length < 1 || args.length > 2) {
            throw new IllegalArgumentException("Usage: GlossaryGenerator <konceptsYmlFile> [sourceClassName]");
        }
        Path konceptsYml = Path.of(args[0]);

        KnowledgeSetSource source;
        if (args.length == 2) {
            source = (KnowledgeSetSource) Class.forName(args[1], true,
                    GlossaryGenerator.class.getClassLoader()).getDeclaredConstructor().newInstance();
        } else {
            List<KnowledgeSetSource> found = new ArrayList<>();
            ServiceLoader.load(KnowledgeSetSource.class, GlossaryGenerator.class.getClassLoader())
                    .forEach(found::add);
            if (found.size() != 1) {
                throw new IllegalStateException("Expected exactly one KnowledgeSetSource on the classpath, found "
                        + found.size() + " — pass the implementation class name as the second argument");
            }
            source = found.getFirst();
        }

        KnowledgeSet knowledgeSet = source.compose();
        List<Declaration> declarations = knowledgeSet.declarations();

        Files.createDirectories(konceptsYml.toAbsolutePath().getParent());
        Files.writeString(konceptsYml, renderYaml(declarations));
        System.out.println("Koncepts written: " + konceptsYml + " — "
                + declarations.size() + " entries from " + source.getClass().getName());
    }

    /**
     * Renders the standard koncepts YAML from the set's declarations.
     *
     * @param declarations the set's declarations
     * @return the koncepts YAML
     */
    static String renderYaml(List<Declaration> declarations) {
        List<Declaration> byName = new ArrayList<>(declarations);
        byName.sort(Comparator.comparing(Declaration::birthFqn));

        Map<PublicId, String> identifierById = new LinkedHashMap<>();
        Map<String, String> identifierToFqn = new LinkedHashMap<>();
        for (Declaration declaration : byName) {
            String identifier = identifier(declaration.birthFqn());
            String prior = identifierToFqn.putIfAbsent(identifier, declaration.birthFqn());
            if (prior != null) {
                throw new IllegalStateException("Koncept identifier collision: \"" + prior
                        + "\" and \"" + declaration.birthFqn() + "\" both reduce to " + identifier);
            }
            identifierById.put(declaration.publicId(), identifier);
        }

        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by rich-surface-glossary from the ledger — DO NOT EDIT.\n");
        sb.append("# Standard koncept definitions for the koncept-asciidoc-extension.\n\n");
        for (Declaration declaration : byName) {
            sb.append(identifierById.get(declaration.publicId())).append(":\n");
            sb.append("  label: ").append(yaml(label(declaration.birthFqn()))).append('\n');
            declaration.definition().ifPresent(def ->
                    sb.append("  definition: ").append(yaml(def)).append('\n'));
            sb.append("  kind: ").append(declaration.kind() == Declaration.Kind.PATTERN
                    ? "pattern" : "concept").append('\n');

            List<String> parentIds = new ArrayList<>();
            List<String> parentLabels = new ArrayList<>();
            for (PublicId parent : declaration.supertypes()) {
                String pid = identifierById.get(parent);
                if (pid != null) {
                    parentIds.add(pid);
                    parentLabels.add(label(fqnOf(byName, parent)));
                }
            }
            if (!parentLabels.isEmpty()) {
                sb.append("  axiom: ").append(yaml("⊑ " + String.join(" ⊓ ", parentLabels))).append('\n');
            }
            if (!parentIds.isEmpty()) {
                sb.append("  broader: [").append(String.join(", ", parentIds)).append("]\n");
            }
            sb.append("  uuids:\n");
            sb.append("    - ").append(declaration.publicId().asUuidArray()[0]).append('\n');
            sb.append('\n');
        }
        return sb.toString();
    }

    private static String fqnOf(List<Declaration> declarations, PublicId id) {
        return declarations.stream().filter(d -> d.publicId().equals(id))
                .map(Declaration::birthFqn).findFirst().orElse("");
    }

    /**
     * The stable {@code k:} identifier for a birth FQN: the tag-stripped name in
     * PascalCase. FQNs are unique within a set, so identifiers are too.
     *
     * @param birthFqn the fully qualified name at birth
     * @return the PascalCase identifier
     */
    static String identifier(String birthFqn) {
        String base = label(birthFqn);
        StringBuilder sb = new StringBuilder();
        for (String word : base.split("[^A-Za-z0-9]+")) {
            if (!word.isEmpty()) {
                sb.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1));
            }
        }
        if (sb.length() == 0) {
            throw new IllegalStateException("Birth FQN reduces to an empty identifier: \"" + birthFqn + "\"");
        }
        if (Character.isDigit(sb.charAt(0))) {
            sb.insert(0, 'N');
        }
        return sb.toString();
    }

    /** The display label: the FQN with its trailing parenthesized semantic tag stripped. */
    static String label(String birthFqn) {
        return birthFqn.replaceAll("\\s*\\([^)]*\\)\\s*$", "").trim();
    }

    /** Renders a scalar as a double-quoted YAML string. */
    private static String yaml(String text) {
        return '"' + text.replace("\\", "\\\\").replace("\"", "\\\"") + '"';
    }
}
